# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kansas City Women in Technology Code of Conduct
description: Kansas City Women in Technology's official Code of Conduct.
baseurl: /CodeOfConduct # the subpath of your site, e.g. /blog
twitter_username: kcwit
github_username:  KansasCityWomeninTechnology
name: Kansas City Women in Technology Code of Conduct

# Build settings
markdown: kramdown